# Generated by Django 3.1.7 on 2021-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='http://placehold.it/500x325', upload_to='posts/img', verbose_name='썸네일 이미지'),
        ),
    ]
